import React from 'react';
import { List, Card, Tag, Typography, Space } from 'antd';
import { UserOutlined, RobotOutlined, ClockCircleOutlined } from '@ant-design/icons';

const { Text } = Typography;

export interface VersionEntry {
    id: string;
    version: number;
    type: 'ai' | 'human';
    title: string;
    timestamp: Date;
    author?: string;
    changes?: string;
}

export interface VersionHistoryListProps {
    /**
     * Array of version history entries
     */
    versions: VersionEntry[];

    /**
     * Callback when a version is clicked
     */
    onClickVersion?: (version: VersionEntry) => void;

    /**
     * Custom class name
     */
    className?: string;
}

/**
 * VersionHistoryList - Version history display for document editing
 * 
 * Shows list of document versions with:
 * - Version number
 * - Type (AI-generated vs human-edited)
 * - Author
 * - Timestamp
 * - Changes summary
 * 
 * @example
 * ```tsx
 * <VersionHistoryList
 *   versions={documentVersions}
 *   onClickVersion={handleVersionClick}
 * />
 * ```
 */
export const VersionHistoryList: React.FC<VersionHistoryListProps> = ({
    versions,
    onClickVersion,
    className,
}) => {
    const getVersionIcon = (type: VersionEntry['type']) => {
        return type === 'ai' ? (
            <RobotOutlined style={{ fontSize: 20, color: '#52c41a' }} />
        ) : (
            <UserOutlined style={{ fontSize: 20, color: '#1677ff' }} />
        );
    };

    const getVersionTag = (type: VersionEntry['type']) => {
        return type === 'ai' ? (
            <Tag color="green">AI Generated</Tag>
        ) : (
            <Tag color="blue">Human Edited</Tag>
        );
    };

    const formatTimeAgo = (date: Date): string => {
        const seconds = Math.floor((Date.now() - date.getTime()) / 1000);
        if (seconds < 60) return `${seconds}s ago`;
        if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
        if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
        return `${Math.floor(seconds / 86400)}d ago`;
    };

    return (
        <Card
            className={className}
            title="Version History"
            style={{
                borderRadius: 12,
                boxShadow: '0 2px 8px rgba(0, 0, 0, 0.08)',
            }}
        >
            <List
                dataSource={versions}
                renderItem={(version) => (
                    <List.Item
                        style={{
                            cursor: onClickVersion ? 'pointer' : 'default',
                            padding: '16px 0',
                            borderBottom: '1px solid #f0f0f0',
                        }}
                        onClick={() => onClickVersion?.(version)}
                    >
                        <List.Item.Meta
                            avatar={getVersionIcon(version.type)}
                            title={
                                <Space size={8}>
                                    <Text strong>v{version.version}: {version.title}</Text>
                                    {getVersionTag(version.type)}
                                </Space>
                            }
                            description={
                                <Space direction="vertical" size={4}>
                                    {version.author && (
                                        <Text type="secondary" style={{ fontSize: 12 }}>
                                            {version.type === 'ai' ? 'Generated by' : 'Edited by'} {version.author}
                                        </Text>
                                    )}

                                    {version.changes && (
                                        <Text type="secondary" style={{ fontSize: 12 }}>
                                            Changes: {version.changes}
                                        </Text>
                                    )}

                                    <Text type="secondary" style={{ fontSize: 11 }}>
                                        <ClockCircleOutlined /> {formatTimeAgo(version.timestamp)} • {version.timestamp.toLocaleString()}
                                    </Text>
                                </Space>
                            }
                        />
                    </List.Item>
                )}
            />
        </Card>
    );
};

VersionHistoryList.displayName = 'VersionHistoryList';
