import React from 'react';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/';
import { Badge } from '@/components/ui/';
import { ScrollArea } from '@/components/ui/';
import { Bot, User, Clock, CheckCircle2 } from 'lucide-react';
import { cn } from '@/lib/utils';

export interface VersionEntry {
    id: string;
    version: number;
    type: 'ai' | 'human';
    title: string;
    timestamp: Date;
    author?: string;
    changes?: string;
}

export interface VersionHistoryListProps {
    versions: VersionEntry[];
    onClickVersion?: (version: VersionEntry) => void;
    className?: string;
}

export const VersionHistoryList: React.FC<VersionHistoryListProps> = ({
    versions,
    onClickVersion,
    className,
}) => {
    const formatTimeAgo = (date: Date): string => {
        const seconds = Math.floor((Date.now() - date.getTime()) / 1000);
        if (seconds < 60) return `${seconds}s ago`;
        if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
        if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
        return `${Math.floor(seconds / 86400)}d ago`;
    };

    return (
        <Card className={cn("shadow-sm", className)}>
            <CardHeader className="pb-3 border-b">
                <CardTitle className="text-base font-medium">Version History</CardTitle>
            </CardHeader>
            <CardContent className="p-0">
                <ScrollArea className="h-[400px]">
                    <div className="divide-y">
                        {versions.map((version) => (
                            <div
                                key={version.id}
                                className={cn(
                                    "p-4 hover:bg-muted/50 transition-colors flex gap-4 items-start group",
                                    onClickVersion && "cursor-pointer"
                                )}
                                onClick={() => onClickVersion?.(version)}
                            >
                                <div className={cn(
                                    "w-10 h-10 rounded-full flex items-center justify-center shrink-0",
                                    version.type === 'ai' ? "bg-green-100 text-green-600" : "bg-blue-100 text-blue-600"
                                )}>
                                    {version.type === 'ai' ? <Bot size={20} /> : <User size={20} />}
                                </div>
                                <div className="flex-1 min-w-0">
                                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                                        <span className="font-semibold text-sm">v{version.version}: {version.title}</span>
                                        <Badge variant="outline" className={cn(
                                            "text-[10px] px-1.5 h-5",
                                            version.type === 'ai' ? "text-green-600 border-green-200 bg-green-50" : "text-blue-600 border-blue-200 bg-blue-50"
                                        )}>
                                            {version.type === 'ai' ? 'AI Generated' : 'Human Edited'}
                                        </Badge>
                                    </div>

                                    <div className="text-xs text-muted-foreground space-y-1">
                                        {version.author && (
                                            <p className="flex items-center gap-1">
                                                <span className="text-foreground/80">{version.type === 'ai' ? 'Generated by' : 'Edited by'}</span> {version.author}
                                            </p>
                                        )}
                                        {version.changes && (
                                            <p className="text-foreground/70 italic">
                                                Changes: &quot;{version.changes}&quot;
                                            </p>
                                        )}
                                        <p className="flex items-center gap-1.5 pt-1">
                                            <Clock size={12} /> {formatTimeAgo(version.timestamp)} • {version.timestamp.toLocaleDateString()}
                                        </p>
                                    </div>
                                </div>

                                <div className="text-green-500 opacity-0 group-hover:opacity-100 transition-opacity">
                                    <CheckCircle2 size={16} />
                                </div>
                            </div>
                        ))}
                        {versions.length === 0 && (
                            <div className="p-8 text-center text-muted-foreground text-sm">
                                No version history available
                            </div>
                        )}
                    </div>
                </ScrollArea>
            </CardContent>
        </Card>
    );
};

VersionHistoryList.displayName = 'VersionHistoryList';
